import { utilityProcess } from "electron";
import path from "node:path";
import type App from "./app";
import { createInterface } from "readline";
import type { ScanData } from "#types/manga";

/**
 * Represents an ongoing scan task, which is used to manage the queue of scan tasks and ensure that only one scan is running at a time.
 */
interface ScanTask {
    id: string;
    directory: string;
    resolve: (mangaData: ScanData & { id: string }) => void;
    reject: (err: Error) => void;
}

export default class MangaScanner {
    private app: App;
    private child: Electron.UtilityProcess | null = null;
    private isScanning = false;
    private queue: ScanTask[] = [];

    constructor(app: App) {
        this.app = app;
    }

    /**
     * Initialize the scanner worker process. This is done lazily when the first scan task is added to the queue, and the worker process is killed when the queue is empty.
     * @private
     */
    private initWorker() {
        if (this.child) return;
        this.child = utilityProcess.fork(
            path.join(
                process.env.APP_ROOT!,
                "dist-electron",
                "scanner.worker.js",
            ),
            [],
            { stdio: "pipe", serviceName: "MangaScanner" },
        );

        if (this.child.stdout) {
            const reader = createInterface({ input: this.child.stdout });

            reader.on("line", (line) => {
                console.debug(`(scanner worker) ${line}`);
            });
        }

        if (this.child.stderr) {
            const reader = createInterface({ input: this.child.stderr });

            reader.on("line", (line) => {
                console.error(`(scanner worker error) ${line}`);
            });
        }

        this.child.on("spawn", () => {
            console.debug(
                "(scanner) Worker process spawned successfully (PID:",
                this.child?.pid,
                ")",
            );
        });

        this.child.on("message", (msg) => {
            const { type, payload } = msg;

            switch (type) {
                case "PROGRESS":
                    console.debug(`(scanner worker) Progress: ${payload.percent}%`);
                    this.app.window?.webContents.send("mangas:scanProgress", payload);
                    break;
                case "DONE":
                    this.finishTask(payload);
                    break;
                case "ERROR":
                    console.error(`Task ${payload.id} failed:`, payload.error);
                    this.finishTask(payload, new Error(payload.error));
                    break;
            }
        });
    }

    /**
     * Will add a scan to the scanner queue
     * @param directory The directory to scan
     * @return A promise that resolves with the ID of the scan task, which can be used to track its progress and completion
     */
    public scan(directory: string): Promise<string> {
        return new Promise((resolve, reject) => {
            // this ID is just for tracking the task. It is not the final ID of the manga in the database, which is generated by SQL
            const id = crypto.randomUUID();

            this.queue.push({
                id,
                directory,
                resolve: (mangaData) => {
                    this.importManga(mangaData)
                },
                reject,
            });

            // we start processing
            this.processNext();

            // resolve immediately with ID so frontend can track it
            resolve(id);
        });
    }

    /**
     * Process the next scan task in the queue if there is one and if we're not already scanning
     * @private
     */
    private processNext() {
        if (this.isScanning || this.queue.length === 0) {
            if (this.queue.length === 0) {
                console.log("(scanner) No more tasks in queue, killing worker");
                this.killWorker();
            }
            return;
        }

        const task = this.queue[0];
        if (!task) return;

        this.initWorker(); // in case the worker was killed after finishing the previous task, be cautious
        this.isScanning = true;

        console.log(`(scanner) Starting task ${task.id}`);

        this.child?.postMessage({
            type: "START",
            payload: {
                id: task.id,
                directory: task.directory,
                userDataFolder: this.app.userDataFolder,
            },
        });
    }

    /**
     * Finish a scan task by its ID, removing it from the queue and resolving or rejecting its promise accordingly. This is called when the worker process sends a "DONE" or "ERROR" message.
     * @param payload The worker finish payload
     * @param error An optional error if the task failed, which will be sent to the frontend and used to reject the task's promise
     * @private
     */
    private finishTask(payload: any, error?: Error) {
        // we find and remove the task
        const taskIndex = this.queue.findIndex((t) => t.id === payload.id);
        if (taskIndex !== -1) {
            const [task] = this.queue.splice(taskIndex, 1);
            if (!task) {
                console.error(
                    `(scanner) Task ${payload.id} not found in queue`,
                );
                return;
            }
            if (error) task.reject(error);
            else task.resolve(payload);
        }

        // notify frontend
        this.app.window?.webContents.send("mangas:scanComplete", {
            ...payload,
            error: error?.message,
        });

        // reset flag and process next item
        this.isScanning = false;
        this.processNext();
    }

    private killWorker() {
        if (this.child) {
            this.child.kill();
            this.child = null;
        }
    }

    public importManga(mangaData: any) {
        console.log("(scanner) Importing manga with data:", mangaData);
    }
}
